### ISSUE TITLE
NUCLEO_F401RE connection failed

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/oob-mbed-os-example-mesh-minimal#2]
I'm using NUCLEO_F401RE+RF233 sheild to test the mesh-minimal. But it always shows "connection failed", with GCC.

The gatway binary file I'm using: https://github.com/ARMmbed/mbed-os-example-client/blob/master/GW_Binary/gateway6LoWPANStatic.bin

The mbed_app.json file:
```
{
    "config": {
        "trace": {
        	"help": "options are true, false",
        	"value": true
        },
        "radio-type":{
            "help": "options are ATMEL, MCR20, NCS36510",
            "value": "ATMEL"
        },
        "mesh-type":{
            "help": "options are MESH_LOWPAN, MESH_THREAD",
            "value": "MESH_LOWPAN"
        }
    },
    "target_overrides": {
        "*": {
            "target.features_add": ["NANOSTACK", "LOWPAN_HOST", "COMMON_PAL"],
            "mbed-mesh-api.6lowpan-nd-device-type": "NET_6LOWPAN_HOST",
            "mbed-mesh-api.6lowpan-nd-channel-page": 0,
            "mbed-mesh-api.6lowpan-nd-channel": 12,
            "mbed-mesh-api.6lowpan-nd-channel-mask": "(1<<12)",
            "mbed-mesh-api.thread-config-panid": "0xDEFA",
            "mbed-mesh-api.thread-master-key": "{0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff}",
            "mbed-mesh-api.thread-config-channel": 12,
            "mbed-mesh-api.heap-size": 10000,
            "mbed-trace.enable": false
        }
    },
    "macros": ["MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES", "MBEDTLS_TEST_NULL_ENTROPY"]
}

```

**Comment by c1728p9** [comment]
Hi @sunsmilearm, are you using the atmel RF shield with a PCB antennna or with a chip antenna?

**Comment by hasnainvirk** [comment]
It doesn't really matter though, but Why do you have this "macros": ["MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES", "MBEDTLS_TEST_NULL_ENTROPY"] ? This example does not use mbedtls at all.

**Comment by sunsmilearm** [comment]
@hasnainvirk without this part, I will get link errors related to tls things.

@c1728p9 I test again and find only GCC can't work. ARMCC and IAR are OK.

**Comment by hasnainvirk** [comment]
@sunsmilearm I am using mbed-os-5.2.0-rc2 and I don't see any link errors. There should be no link errors at all.

**Comment by hasnainvirk** [comment]
@sunsmilearm Okay, I was now able to reproduce those link errors. That is totally absurd as no one is referencing either mbedtls or coap-service. This needs a thorough check to understand what is happening.

**Comment by sunsmilearm** [comment]
@hasnainvirk Did you test ARMCC and IAR? I tried again, no errors when I was using GCC. But in ARMCC and IAR, it has.

**Comment by hasnainvirk** [comment]
@sunsmilearm yeah I tried with armcc and got them.

**Comment by sunsmilearm** [comment]
@hasnainvirk Yes. And the bin file from GCC can't connect and get an IP. Please also take a look:)

**Comment by hasnainvirk** [comment]
@sunsmilearm Alright. It seems that there is some optimization issue here. Probably affecting some timings. Go to mbed-os/tools/profiles/default.json
Under GCC_ARM change "-Os" to "O1" or "O0". I tested it and it works. @c1728p9 russ wrote the radio driver he might be able to help you with driver timing issues. 
About the linker, we can't do much. We need to use these macros because mbed-os build system is beyond me. Seemingly, there is no concept of libraries and everything inside gets compiled as if it were part of the application. If foo=bar and bar doesn't exist, so even if we do not refrence foo, ARMCC and IAR will not let us go through. GCC will let you go through, ofcourse foo will not be linked in. In this particular case, mbedtls is stripped for NUCLEO_F401RE platform because its does not have entropy sources. Whereas coap-service is trying to use those bits of mbedtls which were stripped. I hope this will help.

**Comment by c1728p9** [comment]
I came across this same issue. There is a bug in some ST IIC drivers where a NAK isn't sent at the end a read. Because of this the Atmel RF shield keeps the SDA line held low. There are some open issues for ST IIC problems:
https://github.com/ARMmbed/mbed-os/issues/2959
https://github.com/ARMmbed/mbed-os/issues/2956

If this is the same issue then you should be able to disconnect and reconnect the RF shield, and reset the device and see the first connect work (even with GCC -Os). Subsequent resets won't work since the RF shield is in a bad state.

When I was looking at this, changing the optimization level turned out not to be directly related to the problem. Another bug in the ST GPIO initialization causes the SDA line to get driven high for a brief period of time during init. If this is long enough then the Atmel RF shield will stop driving SDA low allowing IIC to work as expected. The function where this occurs on is HAL_GPIO_Init in TARGET_STM32F4\stm32f4xx_hal_gpio.c. If you need more info on this feel free to message me directly.

**Comment by sunsmilearm** [comment]
@hasnainvirk  @c1728p9  Thanks for your comment.

**Comment by MarceloSalazar** [comment]
Issue fixed. Please re-test on RC3.

**Comment by sunsmilearm** [comment]
@MarceloSalazar Do I need to change anything to make it work? I got the same problem when testing RC3.

the mbed_app.js:
```
{
    "config": {
        "trace": {
        	"help": "options are true, false",
        	"value": true
        },
        "radio-type":{
            "help": "options are ATMEL, MCR20, NCS36510",
            "value": "ATMEL"
        },
        "mesh-type":{
            "help": "options are MESH_LOWPAN, MESH_THREAD",
            "value": "MESH_LOWPAN"
        }
    },
    "target_overrides": {
        "*": {
            "target.features_add": ["NANOSTACK", "LOWPAN_HOST", "COMMON_PAL"],
            "mbed-mesh-api.6lowpan-nd-device-type": "NET_6LOWPAN_HOST",
            "mbed-mesh-api.6lowpan-nd-channel-page": 0,
            "mbed-mesh-api.6lowpan-nd-channel": 12,
            "mbed-mesh-api.6lowpan-nd-channel-mask": "(1<<12)",
            "mbed-mesh-api.thread-config-panid": "0xDEFA",
            "mbed-mesh-api.thread-master-key": "{0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff}",
            "mbed-mesh-api.thread-config-channel": 12,
            "mbed-mesh-api.heap-size": 10000,
            "mbed-trace.enable": false
        }
    }
}

```

**Comment by hasnainvirk** [comment]
@c1728p9 The issue is not resolved. Tested with Atmel and MCR20a.

**Comment by SeppoTakalo** [comment]
@hasnainvirk Did you manually update mbed-OS to RC3.
Is just realised that there might be problems if not done manually. See:  https://github.com/ARMmbed/mbed-os/issues/3037

**Comment by hasnainvirk** [comment]
@c1728p9 @SeppoTakalo @MarceloSalazar Sorry. My mistake. I was missing "mbed-mesh-api.6lowpan-nd-device-type": "NET_6LOWPAN_HOST", in my json file. I have tested with GCC, ARMCC and with ATMEL plus MCR20 radio shields. rc3 solves the issue.

**Comment by MarceloSalazar** [comment]
@hasnainvirk thanks for confirming.
@sunsmilearm do you want to double check?

**Comment by sunsmilearm** [comment]
@MarceloSalazar It works when I typied "mbed update ****rc3". 

But I think "mbed import" is enough  because the mbed-os.lib is already updated to rc3. This may be caused by mbed cache. So I close cache and it works normally.
